package pt.miniFormiga.domain;

public enum TipoOperacao {
    LOGIN,
    LOGOUT,
    VENDA_REGISTADA,
    VENDA_ANULADA,
    FATURA_EMITIDA,
    DEVOLUCAO_REGISTADA,
    FECHO_CAIXA,
    AJUSTE_INVENTARIO,
    ENCOMENDA_CRIADA,
    UTILIZADOR_CRIADO,
    UTILIZADOR_EDITADO,
    UTILIZADOR_DESATIVADO,
    SINCRONIZACAO_INICIADA,
    SINCRONIZACAO_CONCLUIDA,
    OPERACAO_FORA_HORARIO
}
