package pt.miniFormiga.domain;

public enum TipoOperacao {
    VENDA,
    VENDA_FORA_HORARIO,
    VENDA_FINALIZADA,
    LOGIN,
    LOGOUT,
    VENDA_REGISTADA,
    VENDA_ANULADA,
    FATURA_EMITIDA,
    DEVOLUCAO_REGISTADA,
    FECHO_CAIXA,
    FECHO_CAIXA_INICIADO,
    FECHO_CAIXA_CONFIRMADO,
    AJUSTE_STOCK,
    INVENTARIO_FECHADO,
    ACESSO,
    AJUSTE_INVENTARIO,
    ENCOMENDA_CRIADA,
    UTILIZADOR_CRIADO,
    UTILIZADOR_EDITADO,
    UTILIZADOR_DESATIVADO,
    SINCRONIZACAO_INICIADA,
    SINCRONIZACAO_CONCLUIDA,
    OPERACAO_FORA_HORARIO
}
