spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/miniFormiga_central}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:miniFormiga}
spring.datasource.password=${DB_PASSWORD:miniFormiga_dev}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.path=/api/docs
